### ISSUE TITLE
[TicTacToe] Сколько баллов

### ISSUE THREAD

**Issue by pavel-b-novikov** [Magesmith/nsudotnet#5]
вы рассчитывали получить за вашу реализацию задачи?

**Comment by Magesmith** [comment]
Вообще, в задаче указано, что от 6 до 9. Мне хватит и 3, но хотелось бы 6.

**Comment by pavel-b-novikov** [comment]
Ну просто в начале описания задачи крупными буквами стоит дисклеймер, что я знаю что вы можете наговнокодить в codebehind-файлах. Что вы, собственно и сделали. Основная идея была такая, что вы сначала пишете логику в отдельной сборке, а потом наворачиваете фронтенд на чем угодно. Вы же предоставили какой-то странный набор откровенного говнокода на WinForms с несколькими классами в одном файле, с нарушением naming convention-ов, без капли идеи да ещё и на WinForms вместо WPF. Да ещё и за день до дедлайна. Казалось бы, но я даже не знаю какими дополнительными вопросами и заданиями можно довести вашу работу до чего-то потребного.
Я предлагаю поставить вам трояк в зачетку и на этом закончить.

**Comment by Magesmith** [comment]
Я понял. Жаль, но я тут сам виноват, не успею довести до приемлемого вида. Хорошо. За тройкой подойти во вт?

**Comment by pavel-b-novikov** [comment]
Да, за тройкой - во вторник, на общее выставление зачетов
